name: My First GitHub Action

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo "Hello Aditya! Your GitHub Action is working."
